apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
  namespace: argocd
spec:
  project: system
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.10.0
    helm:
      valuesObject:
        admissionWebhooks:
          timeoutSeconds: 30
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
