apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: argocd
spec:
  project: lab
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.15.2
    helm:
      valuesObject:
        crds:
          enabled: true
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
