apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: argocd
spec:
  project: system
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.15.2
    helm:
      valuesObject:
        crds:
          enabled: true
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
