server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      traefik.ingress.kubernetes.io/router.tls: "true"
    ingressClassName: traefik
    hosts:
      - host: vault.lab.alsheykh.com
        paths: []
    tls:
      - secretName: vault-tls
        hosts:
          - vault.lab.alsheykh.com
ui:
  enabled: true